# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/xorg/eric/Sportfest/ui/DatabaseForm.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 642)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/appicons/dbedit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = FTableWidget(self.centralWidget)
        self.tableWidget.setEnabled(False)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuDatei = QtWidgets.QMenu(self.menuBar)
        self.menuDatei.setObjectName("menuDatei")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAdd = QtWidgets.QAction(MainWindow)
        self.actionAdd.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/toolbar_icons_48/addstudent"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd.setIcon(icon1)
        self.actionAdd.setObjectName("actionAdd")
        self.actionRemove = QtWidgets.QAction(MainWindow)
        self.actionRemove.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/toolbar_icons_48/delstudent"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRemove.setIcon(icon2)
        self.actionRemove.setObjectName("actionRemove")
        self.actionMoveKlasse = QtWidgets.QAction(MainWindow)
        self.actionMoveKlasse.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/toolbar_icons_48/graduate"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMoveKlasse.setIcon(icon3)
        self.actionMoveKlasse.setObjectName("actionMoveKlasse")
        self.actionNeue_Datenbank = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/menu_icons_16/new"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNeue_Datenbank.setIcon(icon4)
        self.actionNeue_Datenbank.setObjectName("actionNeue_Datenbank")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/menu_icons_16/save"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon5)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/menu_icons_16/save-as"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveAs.setIcon(icon6)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/menu_icons_16/open"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon7)
        self.actionOpen.setObjectName("actionOpen")
        self.actionFromExcel = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/menu_icons_16/fromexcel"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFromExcel.setIcon(icon8)
        self.actionFromExcel.setObjectName("actionFromExcel")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/menu_icons_16/exit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon9)
        self.actionClose.setObjectName("actionClose")
        self.actionSort = QtWidgets.QAction(MainWindow)
        self.actionSort.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/toolbar_icons_48/sort"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSort.setIcon(icon10)
        self.actionSort.setObjectName("actionSort")
        self.menuDatei.addAction(self.actionNeue_Datenbank)
        self.menuDatei.addAction(self.actionFromExcel)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionOpen)
        self.menuDatei.addAction(self.actionSave)
        self.menuDatei.addAction(self.actionSaveAs)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionClose)
        self.menuBar.addAction(self.menuDatei.menuAction())
        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addAction(self.actionRemove)
        self.toolBar.addAction(self.actionMoveKlasse)
        self.toolBar.addAction(self.actionSort)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Datenbankeditor - FFSportfest"))
        self.tableWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>In dieser Tabelle können die Ergebnisse des Schülers bearbeitet werden. Es gibt einige Sondertasten um die Arbeit effizienter zu gestalten:</p><ul><li>Enter = Nächste Zeile, gleiche Spalte</li><li>Tab = Nächste Spalte, gleiche Zeile</li><li>Backspace = An den Anfang der Zeile</li><li>Entf. = Ergebnis löschen</li></ul></body></html>"))
        self.menuDatei.setTitle(_translate("MainWindow", "Datei"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionAdd.setText(_translate("MainWindow", "Schüler hinzufügen"))
        self.actionAdd.setToolTip(_translate("MainWindow", "Neuen Schüler hinzufügen"))
        self.actionRemove.setText(_translate("MainWindow", "Schüler entfernen"))
        self.actionRemove.setToolTip(_translate("MainWindow", "Entfernt den ausgewählten Schüler"))
        self.actionMoveKlasse.setText(_translate("MainWindow", "Klassen verschieben"))
        self.actionMoveKlasse.setToolTip(_translate("MainWindow", "<html><head/><body><p>Verschiebt die Klassen um ein Jahr (5. Klasse → 6. Klasse, 6. Klasse → 7. Klasse, usw.)</p></body></html>"))
        self.actionNeue_Datenbank.setText(_translate("MainWindow", "Neue Datenbank"))
        self.actionNeue_Datenbank.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Speichern"))
        self.actionSave.setToolTip(_translate("MainWindow", "Speichert die Datenbank ab"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "Speichern unter..."))
        self.actionSaveAs.setToolTip(_translate("MainWindow", "Speichert die Datenbank unter neuem Namen ab"))
        self.actionSaveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionOpen.setText(_translate("MainWindow", "Öffnen..."))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionFromExcel.setText(_translate("MainWindow", "Datenbank aus Excel-Tabelle erstellen"))
        self.actionFromExcel.setShortcut(_translate("MainWindow", "Ctrl+Shift+N"))
        self.actionClose.setText(_translate("MainWindow", "Beenden"))
        self.actionSort.setText(_translate("MainWindow", "Sortieren"))
        self.actionSort.setToolTip(_translate("MainWindow", "<html><head/><body><p>Sortiert die Schüler nach Nach- und Vornamen</p></body></html>"))

from FTableWidget import FTableWidget
import oxyicons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

