# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/xorg/eric/Sportfest/ui/EvaluateForm.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/appicons/auswertung"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.filterFirstCombo = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterFirstCombo.sizePolicy().hasHeightForWidth())
        self.filterFirstCombo.setSizePolicy(sizePolicy)
        self.filterFirstCombo.setMinimumSize(QtCore.QSize(100, 0))
        self.filterFirstCombo.setObjectName("filterFirstCombo")
        self.filterFirstCombo.addItem("")
        self.filterFirstCombo.addItem("")
        self.filterFirstCombo.addItem("")
        self.gridLayout_2.addWidget(self.filterFirstCombo, 1, 1, 1, 1)
        self.filterSecondCombo = QtWidgets.QComboBox(self.groupBox)
        self.filterSecondCombo.setMinimumSize(QtCore.QSize(120, 0))
        self.filterSecondCombo.setObjectName("filterSecondCombo")
        self.filterSecondCombo.addItem("")
        self.filterSecondCombo.addItem("")
        self.filterSecondCombo.addItem("")
        self.gridLayout_2.addWidget(self.filterSecondCombo, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 2, 1, 1)
        self.sortFirstCombo = QtWidgets.QComboBox(self.groupBox_2)
        self.sortFirstCombo.setObjectName("sortFirstCombo")
        self.gridLayout_3.addWidget(self.sortFirstCombo, 0, 1, 1, 1)
        self.sortSecondCombo = QtWidgets.QComboBox(self.groupBox_2)
        self.sortSecondCombo.setObjectName("sortSecondCombo")
        self.gridLayout_3.addWidget(self.sortSecondCombo, 0, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setStyleSheet("")
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionRefreshData = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/toolbar_icons_48/refresh"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/themes/oxygen/32x32/actions/view-refresh.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.actionRefreshData.setIcon(icon1)
        self.actionRefreshData.setObjectName("actionRefreshData")
        self.actionRecalc = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/toolbar_icons_48/calc"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/themes/oxygen/128x128/apps/accessories-calculator.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.actionRecalc.setIcon(icon2)
        self.actionRecalc.setObjectName("actionRecalc")
        self.actionRePlace = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/toolbar_icons_48/favorites"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/themes/oxygen/128x128/places/favorites.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.actionRePlace.setIcon(icon3)
        self.actionRePlace.setObjectName("actionRePlace")
        self.actionPPreview = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/toolbar_icons_48/printpreview"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/themes/oxygen/48x48/actions/document-print-preview.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.actionPPreview.setIcon(icon4)
        self.actionPPreview.setObjectName("actionPPreview")
        self.actionDoPrint = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/toolbar_icons_48/print"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDoPrint.setIcon(icon5)
        self.actionDoPrint.setObjectName("actionDoPrint")
        self.actionClose = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/toolbar_icons_48/exitlg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClose.setIcon(icon6)
        self.actionClose.setMenuRole(QtWidgets.QAction.QuitRole)
        self.actionClose.setObjectName("actionClose")
        self.actionUrkunde = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/toolbar_icons_48/urkunde"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUrkunde.setIcon(icon7)
        self.actionUrkunde.setObjectName("actionUrkunde")
        self.toolBar.addAction(self.actionRefreshData)
        self.toolBar.addAction(self.actionRecalc)
        self.toolBar.addAction(self.actionRePlace)
        self.toolBar.addAction(self.actionPPreview)
        self.toolBar.addAction(self.actionDoPrint)
        self.toolBar.addAction(self.actionUrkunde)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionClose)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Auswertung - FFSportfest"))
        self.groupBox.setTitle(_translate("MainWindow", "Filter"))
        self.label.setText(_translate("MainWindow", "Zeige... "))
        self.filterFirstCombo.setItemText(0, _translate("MainWindow", "alle Schüler"))
        self.filterFirstCombo.setItemText(1, _translate("MainWindow", "Jungen"))
        self.filterFirstCombo.setItemText(2, _translate("MainWindow", "Mädchen"))
        self.filterSecondCombo.setItemText(0, _translate("MainWindow", "aller Klassen"))
        self.filterSecondCombo.setItemText(1, _translate("MainWindow", "der 5. Klassen"))
        self.filterSecondCombo.setItemText(2, _translate("MainWindow", "der Klasse 5.1"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Sortierung"))
        self.label_2.setText(_translate("MainWindow", "Sortiere erst nach..."))
        self.label_3.setText(_translate("MainWindow", "... und dann nach ..."))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionRefreshData.setText(_translate("MainWindow", "Daten aktualisieren"))
        self.actionRefreshData.setIconText(_translate("MainWindow", " Daten aktualisieren"))
        self.actionRefreshData.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ruft die Daten manuell aus dem Hauptfenster ab. Verwenden Sie diese Funktion wenn die Daten nicht automatisch übertragen werden.</p></body></html>"))
        self.actionRefreshData.setShortcut(_translate("MainWindow", "F5"))
        self.actionRecalc.setText(_translate("MainWindow", "Neu berechnen"))
        self.actionRecalc.setToolTip(_translate("MainWindow", "<html><head/><body><p>Berechnet die Punkte und Noten erneut. Dies sollte normalerweise automatisch passieren, es kann aber mit dieser Funktion erzwungen werden.</p></body></html>"))
        self.actionRePlace.setText(_translate("MainWindow", "Plätze neu ermitteln"))
        self.actionRePlace.setIconText(_translate("MainWindow", " Plätze neu ermitteln"))
        self.actionRePlace.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ermittelt die Platzierungen für den ausgewählten Filter neu. Dies passiert normalerweise automatisch, kann aber mit dieser Funktion erzwungen werden.</p></body></html>"))
        self.actionPPreview.setText(_translate("MainWindow", "Druckvorschau"))
        self.actionPPreview.setIconText(_translate("MainWindow", " Druckvorschau"))
        self.actionPPreview.setToolTip(_translate("MainWindow", "<html><head/><body><p>Zeigt eine Vorschau des Ausdrucks.</p></body></html>"))
        self.actionPPreview.setShortcut(_translate("MainWindow", "Ctrl+Shift+P"))
        self.actionDoPrint.setText(_translate("MainWindow", "Drucken"))
        self.actionDoPrint.setToolTip(_translate("MainWindow", "<html><head/><body><p>Druckt die Ergebnisse mit dem ausgewählten Filter und Sortierung. Eine Vorschau des Ausdrucks kann mit <span style=\" font-style:italic;\">Druckvorschau</span> angezeigt werden.</p></body></html>"))
        self.actionDoPrint.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionClose.setText(_translate("MainWindow", "Schließen"))
        self.actionClose.setToolTip(_translate("MainWindow", "<html><head/><body><p>Schließt das Auswertungsfenster.</p></body></html>"))
        self.actionUrkunde.setText(_translate("MainWindow", "Urkunden erstellen"))
        self.actionUrkunde.setToolTip(_translate("MainWindow", "Erstellt Urkunden (beta)"))

import oxyicons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

