# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/xorg/Python IDE/Sportfest/ui/MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(939, 686)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/appicons/main"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = FTableWidget(self.centralWidget)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.klasseCombo = QtWidgets.QComboBox(self.groupBox)
        self.klasseCombo.setObjectName("klasseCombo")
        self.gridLayout_2.addWidget(self.klasseCombo, 0, 1, 1, 1)
        self.geschlechtCombo = QtWidgets.QComboBox(self.groupBox)
        self.geschlechtCombo.setObjectName("geschlechtCombo")
        self.gridLayout_2.addWidget(self.geschlechtCombo, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.geschlechtEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.geschlechtEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geschlechtEdit.sizePolicy().hasHeightForWidth())
        self.geschlechtEdit.setSizePolicy(sizePolicy)
        self.geschlechtEdit.setReadOnly(True)
        self.geschlechtEdit.setObjectName("geschlechtEdit")
        self.gridLayout_3.addWidget(self.geschlechtEdit, 2, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.groupBox_2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_3.addWidget(self.line_6, 17, 0, 1, 2)
        self.wurfPunkteEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.wurfPunkteEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wurfPunkteEdit.sizePolicy().hasHeightForWidth())
        self.wurfPunkteEdit.setSizePolicy(sizePolicy)
        self.wurfPunkteEdit.setReadOnly(True)
        self.wurfPunkteEdit.setObjectName("wurfPunkteEdit")
        self.gridLayout_3.addWidget(self.wurfPunkteEdit, 16, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.groupBox_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_3.addWidget(self.line_5, 14, 0, 1, 2)
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 13, 0, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 16, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 9, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 8, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox_2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 11, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.vornameEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.vornameEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vornameEdit.sizePolicy().hasHeightForWidth())
        self.vornameEdit.setSizePolicy(sizePolicy)
        self.vornameEdit.setReadOnly(True)
        self.vornameEdit.setObjectName("vornameEdit")
        self.gridLayout_3.addWidget(self.vornameEdit, 1, 1, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.nameEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nameEdit.sizePolicy().hasHeightForWidth())
        self.nameEdit.setSizePolicy(sizePolicy)
        self.nameEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.nameEdit.setReadOnly(True)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout_3.addWidget(self.nameEdit, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.wurfMeterEdit = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wurfMeterEdit.sizePolicy().hasHeightForWidth())
        self.wurfMeterEdit.setSizePolicy(sizePolicy)
        self.wurfMeterEdit.setObjectName("wurfMeterEdit")
        self.gridLayout_3.addWidget(self.wurfMeterEdit, 15, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.klasseEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.klasseEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.klasseEdit.sizePolicy().hasHeightForWidth())
        self.klasseEdit.setSizePolicy(sizePolicy)
        self.klasseEdit.setReadOnly(True)
        self.klasseEdit.setObjectName("klasseEdit")
        self.gridLayout_3.addWidget(self.klasseEdit, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 7, 0, 1, 2)
        self.LaufPunkteEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.LaufPunkteEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LaufPunkteEdit.sizePolicy().hasHeightForWidth())
        self.LaufPunkteEdit.setSizePolicy(sizePolicy)
        self.LaufPunkteEdit.setReadOnly(True)
        self.LaufPunkteEdit.setObjectName("LaufPunkteEdit")
        self.gridLayout_3.addWidget(self.LaufPunkteEdit, 9, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 6, 0, 1, 1)
        self.sprintSecEdit = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sprintSecEdit.sizePolicy().hasHeightForWidth())
        self.sprintSecEdit.setSizePolicy(sizePolicy)
        self.sprintSecEdit.setObjectName("sprintSecEdit")
        self.gridLayout_3.addWidget(self.sprintSecEdit, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 18, 0, 1, 1)
        self.sprintPunkteEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.sprintPunkteEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sprintPunkteEdit.sizePolicy().hasHeightForWidth())
        self.sprintPunkteEdit.setSizePolicy(sizePolicy)
        self.sprintPunkteEdit.setAutoFillBackground(False)
        self.sprintPunkteEdit.setFrame(True)
        self.sprintPunkteEdit.setReadOnly(True)
        self.sprintPunkteEdit.setObjectName("sprintPunkteEdit")
        self.gridLayout_3.addWidget(self.sprintPunkteEdit, 6, 1, 1, 1)
        self.sprungMeterEdit = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sprungMeterEdit.sizePolicy().hasHeightForWidth())
        self.sprungMeterEdit.setSizePolicy(sizePolicy)
        self.sprungMeterEdit.setObjectName("sprungMeterEdit")
        self.gridLayout_3.addWidget(self.sprungMeterEdit, 12, 1, 1, 1)
        self.LaufSecEdit = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LaufSecEdit.sizePolicy().hasHeightForWidth())
        self.LaufSecEdit.setSizePolicy(sizePolicy)
        self.LaufSecEdit.setObjectName("LaufSecEdit")
        self.gridLayout_3.addWidget(self.LaufSecEdit, 8, 1, 1, 1)
        self.sprungPunkteEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.sprungPunkteEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sprungPunkteEdit.sizePolicy().hasHeightForWidth())
        self.sprungPunkteEdit.setSizePolicy(sizePolicy)
        self.sprungPunkteEdit.setReadOnly(True)
        self.sprungPunkteEdit.setObjectName("sprungPunkteEdit")
        self.gridLayout_3.addWidget(self.sprungPunkteEdit, 13, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_3.addWidget(self.label_30, 12, 0, 1, 1)
        self.punkteTotalEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.punkteTotalEdit.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.punkteTotalEdit.sizePolicy().hasHeightForWidth())
        self.punkteTotalEdit.setSizePolicy(sizePolicy)
        self.punkteTotalEdit.setObjectName("punkteTotalEdit")
        self.gridLayout_3.addWidget(self.punkteTotalEdit, 18, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 15, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 21, 0, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.groupBox_2)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout_3.addWidget(self.line_10, 19, 0, 1, 2)
        self.openEvaluationButton = QtWidgets.QCommandLinkButton(self.groupBox_2)
        self.openEvaluationButton.setEnabled(True)
        self.openEvaluationButton.setObjectName("openEvaluationButton")
        self.gridLayout_3.addWidget(self.openEvaluationButton, 20, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout.addWidget(self.widget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 939, 24))
        self.menuBar.setObjectName("menuBar")
        self.menuDatei = QtWidgets.QMenu(self.menuBar)
        self.menuDatei.setObjectName("menuDatei")
        self.menu_ber = QtWidgets.QMenu(self.menuBar)
        self.menu_ber.setObjectName("menu_ber")
        self.menuZusammenarbeit = QtWidgets.QMenu(self.menuBar)
        self.menuZusammenarbeit.setObjectName("menuZusammenarbeit")
        self.menuPortableDatei = QtWidgets.QMenu(self.menuBar)
        self.menuPortableDatei.setObjectName("menuPortableDatei")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionBeenden = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/menu_icons_16/exit"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBeenden.setIcon(icon1)
        self.actionBeenden.setMenuRole(QtWidgets.QAction.NoRole)
        self.actionBeenden.setObjectName("actionBeenden")
        self.actionDatenbank_laden = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/menu_icons_16/open"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDatenbank_laden.setIcon(icon2)
        self.actionDatenbank_laden.setObjectName("actionDatenbank_laden")
        self.actionDatenbank_speichern = QtWidgets.QAction(MainWindow)
        self.actionDatenbank_speichern.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/menu_icons_16/save"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDatenbank_speichern.setIcon(icon3)
        self.actionDatenbank_speichern.setObjectName("actionDatenbank_speichern")
        self.actionDatenbank_speichern_unter = QtWidgets.QAction(MainWindow)
        self.actionDatenbank_speichern_unter.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/menu_icons_16/save-as"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDatenbank_speichern_unter.setIcon(icon4)
        self.actionDatenbank_speichern_unter.setObjectName("actionDatenbank_speichern_unter")
        self.action_ber_FFSportfest = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/menu_icons_16/about"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ber_FFSportfest.setIcon(icon5)
        self.action_ber_FFSportfest.setMenuRole(QtWidgets.QAction.AboutRole)
        self.action_ber_FFSportfest.setObjectName("action_ber_FFSportfest")
        self.action_ber_Qt = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/appicons/qt"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_ber_Qt.setIcon(icon6)
        self.action_ber_Qt.setMenuRole(QtWidgets.QAction.AboutQtRole)
        self.action_ber_Qt.setObjectName("action_ber_Qt")
        self.actionDrucken = QtWidgets.QAction(MainWindow)
        self.actionDrucken.setEnabled(False)
        self.actionDrucken.setObjectName("actionDrucken")
        self.actionAuswertung_ffnen = QtWidgets.QAction(MainWindow)
        self.actionAuswertung_ffnen.setObjectName("actionAuswertung_ffnen")
        self.actionDatenbank_bearbeiten_2 = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/menu_icons_16/database"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDatenbank_bearbeiten_2.setIcon(icon7)
        self.actionDatenbank_bearbeiten_2.setObjectName("actionDatenbank_bearbeiten_2")
        self.actionHilfe = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/menu_icons_16/help"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHilfe.setIcon(icon8)
        self.actionHilfe.setObjectName("actionHilfe")
        self.actionMLN_erstellen = QtWidgets.QAction(MainWindow)
        self.actionMLN_erstellen.setObjectName("actionMLN_erstellen")
        self.actionExport = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/menu_icons_16/export"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon9)
        self.actionExport.setObjectName("actionExport")
        self.actionImport = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/menu_icons_16/import"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImport.setIcon(icon10)
        self.actionImport.setObjectName("actionImport")
        self.actionSpeichernPortable = QtWidgets.QAction(MainWindow)
        self.actionSpeichernPortable.setIcon(icon3)
        self.actionSpeichernPortable.setObjectName("actionSpeichernPortable")
        self.actionBeendenPortable = QtWidgets.QAction(MainWindow)
        self.actionBeendenPortable.setIcon(icon1)
        self.actionBeendenPortable.setMenuRole(QtWidgets.QAction.NoRole)
        self.actionBeendenPortable.setObjectName("actionBeendenPortable")
        self.actionEinstellungen = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/menu_icons_16/settings"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEinstellungen.setIcon(icon11)
        self.actionEinstellungen.setMenuRole(QtWidgets.QAction.NoRole)
        self.actionEinstellungen.setObjectName("actionEinstellungen")
        self.actionEinstellungenPortable = QtWidgets.QAction(MainWindow)
        self.actionEinstellungenPortable.setIcon(icon11)
        self.actionEinstellungenPortable.setMenuRole(QtWidgets.QAction.NoRole)
        self.actionEinstellungenPortable.setObjectName("actionEinstellungenPortable")
        self.menuDatei.addAction(self.actionDatenbank_bearbeiten_2)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionDatenbank_laden)
        self.menuDatei.addAction(self.actionDatenbank_speichern)
        self.menuDatei.addAction(self.actionDatenbank_speichern_unter)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionEinstellungen)
        self.menuDatei.addSeparator()
        self.menuDatei.addAction(self.actionBeenden)
        self.menu_ber.addAction(self.actionHilfe)
        self.menu_ber.addSeparator()
        self.menu_ber.addAction(self.action_ber_FFSportfest)
        self.menu_ber.addAction(self.action_ber_Qt)
        self.menuZusammenarbeit.addAction(self.actionExport)
        self.menuZusammenarbeit.addAction(self.actionImport)
        self.menuPortableDatei.addAction(self.actionSpeichernPortable)
        self.menuPortableDatei.addSeparator()
        self.menuPortableDatei.addAction(self.actionEinstellungenPortable)
        self.menuPortableDatei.addSeparator()
        self.menuPortableDatei.addAction(self.actionBeendenPortable)
        self.menuBar.addAction(self.menuDatei.menuAction())
        self.menuBar.addAction(self.menuPortableDatei.menuAction())
        self.menuBar.addAction(self.menuZusammenarbeit.menuAction())
        self.menuBar.addAction(self.menu_ber.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sportfest - © Fabian Schillig 2017"))
        self.tableWidget.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>In dieser Tabelle können die Ergebnisse des Schülers bearbeitet werden. Es gibt einige Sondertasten um die Arbeit effizienter zu gestalten:</p><ul><li>Enter = Nächste Zeile, gleiche Spalte</li><li>Tab = Nächste Spalte, gleiche Zeile</li><li>Backspace = An den Anfang der Zeile</li><li>Entf. = Ergebnis löschen</li></ul></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Filter"))
        self.label.setText(_translate("MainWindow", "Klasse: "))
        self.klasseCombo.setToolTip(_translate("MainWindow", "<html><head/><body><p>Die Klasse(n) die angezeigt werden. Es können Klassen (z.B. 7.1), Klassenstufen (Alle 7. Klassen) oder alle Klassen angezeigt werden.</p></body></html>"))
        self.klasseCombo.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Die Klasse(n) die angezeigt werden. Es können Klassen (z.B. 7.1), Klassenstufen (Alle 7. Klassen) oder alle Klassen angezeigt werden.</p></body></html>"))
        self.geschlechtCombo.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Mit dieser Einstellung können nur Jungen, nur Mädchen oder alle angezeigt werden.</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Geschlecht: "))
        self.groupBox_2.setTitle(_translate("MainWindow", "Schülerdetails"))
        self.geschlechtEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Das Geschlecht des Schülers. Dieses Feld kann nicht bearbeitet werden - wählen Sie im Menü &quot;Schüler&quot; die Option &quot;Schüler bearbeiten&quot; an um Schüler zu bearbeiten.</p></body></html>"))
        self.geschlechtEdit.setPlaceholderText(_translate("MainWindow", "sonstige"))
        self.wurfPunkteEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Die Punktezahl und Note des Schülers für Ballwurf / Kugelstoßen. Dieses Feld kann nicht bearbeitet werden und wird automatisch ausgerechnet.</p></body></html>"))
        self.wurfPunkteEdit.setPlaceholderText(_translate("MainWindow", "0 / 0"))
        self.label_31.setText(_translate("MainWindow", "Punkte / Note:"))
        self.label_33.setText(_translate("MainWindow", "Punkte / Note:"))
        self.label_11.setText(_translate("MainWindow", "Punkte / Note:"))
        self.label_10.setText(_translate("MainWindow", "Lauf (min:sec):"))
        self.label_3.setText(_translate("MainWindow", "Name: "))
        self.vornameEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Der Vorname des Schülers. Dieses Feld kann nicht bearbeitet werden - wählen Sie im Menü &quot;Schüler&quot; die Option &quot;Schüler bearbeiten&quot; an um Schüler zu bearbeiten.</p></body></html>"))
        self.vornameEdit.setPlaceholderText(_translate("MainWindow", "Max"))
        self.nameEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Der Nachname des Schülers. Dieses Feld kann nicht bearbeitet werden - wählen Sie im Menü &quot;Schüler&quot; die Option &quot;Schüler bearbeiten&quot; an um Schüler zu bearbeiten.</p></body></html>"))
        self.nameEdit.setPlaceholderText(_translate("MainWindow", "Mustermann"))
        self.label_4.setText(_translate("MainWindow", "Vorname: "))
        self.wurfMeterEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Das Ballwurf- bzw. Kugelstoß-Ergebnis des Schülers in Metern. Dieses Feld kann hier oder in der Tabelle links bearbeitet werden. Änderungen werden sofort übernommen. Punkte und Note werden automatisch ausgerechnet.</p></body></html>"))
        self.wurfMeterEdit.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Geschlecht: "))
        self.klasseEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Die Klasse des Schülers. Dieses Feld kann nicht bearbeitet werden - wählen Sie im Menü &quot;Schüler&quot; die Option &quot;Schüler bearbeiten&quot; an um Schüler zu bearbeiten.</p></body></html>"))
        self.klasseEdit.setPlaceholderText(_translate("MainWindow", "0.0"))
        self.label_6.setText(_translate("MainWindow", "Klasse:"))
        self.LaufPunkteEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Die Punktezahl und Note des Schülers für Ausdauerlauf. Dieses Feld kann nicht bearbeitet werden und wird automatisch ausgerechnet.</p></body></html>"))
        self.LaufPunkteEdit.setPlaceholderText(_translate("MainWindow", "0 / 0"))
        self.label_8.setText(_translate("MainWindow", "Sprint (sec):"))
        self.label_9.setText(_translate("MainWindow", "Punkte / Note:"))
        self.sprintSecEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Die Sprintzeit des Schülers in Sekunden. Dieses Feld kann hier oder in der Tabelle links bearbeitet werden. Änderungen werden sofort übernommen. Punkte und Note werden automatisch ausgerechnet.</p></body></html>"))
        self.sprintSecEdit.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "Punkte gesamt:"))
        self.sprintPunkteEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Die Punktezahl und Note des Schülers für Sprint. Dieses Feld kann nicht bearbeitet werden und wird automatisch ausgerechnet.</p></body></html>"))
        self.sprintPunkteEdit.setPlaceholderText(_translate("MainWindow", "0 / 0"))
        self.sprungMeterEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Das Weitsprungergebnis des Schülers in Metern. Dieses Feld kann hier oder in der Tabelle links bearbeitet werden. Änderungen werden sofort übernommen. Punkte und Note werden automatisch ausgerechnet.</p></body></html>"))
        self.sprungMeterEdit.setPlaceholderText(_translate("MainWindow", "0"))
        self.LaufSecEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Die Ausdauerlauf-Zeit des Schülers in Minuten und Sekunden. Die Eingabe muss in M:SS bzw. MM:SS erfolgen (M = Minuten, S = Sekunden - z.B. 1:25 für 1 Minute und 25 Sekunden). Dieses Feld kann hier oder in der Tabelle links bearbeitet werden. Änderungen werden sofort übernommen. Punkte und Note werden automatisch ausgerechnet.</p></body></html>"))
        self.LaufSecEdit.setPlaceholderText(_translate("MainWindow", "0:00"))
        self.sprungPunkteEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Die Punktezahl und Note des Schülers für Weitsprung. Dieses Feld kann nicht bearbeitet werden und wird automatisch ausgerechnet.</p></body></html>"))
        self.sprungPunkteEdit.setPlaceholderText(_translate("MainWindow", "0 / 0"))
        self.label_30.setText(_translate("MainWindow", "Weitsprung (m):"))
        self.punkteTotalEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Die Gesamtpunktzahl des Schülers. Dieses Feld kann nicht bearbeitet werden und wird automatisch ausgerechnet.</p></body></html>"))
        self.punkteTotalEdit.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_32.setText(_translate("MainWindow", "Wurf (m):"))
        self.openEvaluationButton.setText(_translate("MainWindow", "Auswertung öffnen"))
        self.openEvaluationButton.setDescription(_translate("MainWindow", "Platzier. ermitteln, Drucken, ..."))
        self.menuDatei.setTitle(_translate("MainWindow", "Datei"))
        self.menu_ber.setTitle(_translate("MainWindow", "Hilfe"))
        self.menuZusammenarbeit.setTitle(_translate("MainWindow", "Zusammenarbeit"))
        self.menuPortableDatei.setTitle(_translate("MainWindow", "Datei"))
        self.actionBeenden.setText(_translate("MainWindow", "Beenden"))
        self.actionBeenden.setToolTip(_translate("MainWindow", "Beendet das Programm"))
        self.actionBeenden.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionDatenbank_laden.setText(_translate("MainWindow", "Datenbank öffnen"))
        self.actionDatenbank_laden.setToolTip(_translate("MainWindow", "Öffnet eine Datenbank"))
        self.actionDatenbank_laden.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionDatenbank_speichern.setText(_translate("MainWindow", "Datenbank speichern"))
        self.actionDatenbank_speichern.setToolTip(_translate("MainWindow", "Speichert die Datenbank unter dem gleichen Dateinamen ab"))
        self.actionDatenbank_speichern.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionDatenbank_speichern_unter.setText(_translate("MainWindow", "Datenbank speichern unter..."))
        self.actionDatenbank_speichern_unter.setToolTip(_translate("MainWindow", "Speichert die Datenbank unter einem anderen Namen ab"))
        self.actionDatenbank_speichern_unter.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.action_ber_FFSportfest.setText(_translate("MainWindow", "Über FFSportfest.."))
        self.action_ber_Qt.setText(_translate("MainWindow", "Über Qt..."))
        self.actionDrucken.setText(_translate("MainWindow", "Drucken..."))
        self.actionDrucken.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionAuswertung_ffnen.setText(_translate("MainWindow", "Auswertung öffnen"))
        self.actionDatenbank_bearbeiten_2.setText(_translate("MainWindow", "Datenbankeditor"))
        self.actionDatenbank_bearbeiten_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Werkzeug um Datenbanken zu bearbeiten oder zu erstellen.</p></body></html>"))
        self.actionDatenbank_bearbeiten_2.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionHilfe.setText(_translate("MainWindow", "Hilfe..."))
        self.actionHilfe.setToolTip(_translate("MainWindow", "Zeigt die Programmdokumentation an"))
        self.actionHilfe.setShortcut(_translate("MainWindow", "F1"))
        self.actionMLN_erstellen.setText(_translate("MainWindow", "MLN erstellen..."))
        self.actionExport.setText(_translate("MainWindow", "FMD exportieren…"))
        self.actionExport.setToolTip(_translate("MainWindow", "<html><head/><body><p>Exportiert eine Klasse oder Klassenstufe in eine mobile Datenbank. Diese Funktion kann verwendet werden wenn an mehreren Computern Ergebnisse erfasst werden.</p></body></html>"))
        self.actionExport.setShortcut(_translate("MainWindow", "Ctrl+Shift+E"))
        self.actionImport.setText(_translate("MainWindow", "FMD importieren…"))
        self.actionImport.setToolTip(_translate("MainWindow", "<html><head/><body><p>Importiert die Ergebnisse einer Klasse oder Klassenstufe aus einer mobile Datenbank. Diese Funktion kann verwendet werden wenn an mehreren Computern Ergebnisse erfasst werden.</p></body></html>"))
        self.actionImport.setShortcut(_translate("MainWindow", "Ctrl+Shift+I"))
        self.actionSpeichernPortable.setText(_translate("MainWindow", "Speichern"))
        self.actionSpeichernPortable.setToolTip(_translate("MainWindow", "<html><head/><body><p>Speichert die Ergebnisse</p></body></html>"))
        self.actionSpeichernPortable.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionBeendenPortable.setText(_translate("MainWindow", "Beenden"))
        self.actionBeendenPortable.setToolTip(_translate("MainWindow", "<html><head/><body><p>Speichert die Ergebnisse und beendet das Programm</p></body></html>"))
        self.actionBeendenPortable.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionEinstellungen.setText(_translate("MainWindow", "Einstellungen"))
        self.actionEinstellungenPortable.setText(_translate("MainWindow", "Einstellungen"))
        self.actionEinstellungenPortable.setToolTip(_translate("MainWindow", "Öffnet den Einstellungsdialog"))

from FTableWidget import FTableWidget
import oxyicons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

