# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/xorg/eric/Sportfest/ui/SettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(581, 333)
        Dialog.setSizeGripEnabled(True)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        spacerItem = QtWidgets.QSpacerItem(71, 31, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setObjectName("okButton")
        self.hboxlayout.addWidget(self.okButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.hboxlayout, 1, 0, 1, 2)
        self.widget = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.loadLastDb = QtWidgets.QCheckBox(self.groupBox)
        self.loadLastDb.setObjectName("loadLastDb")
        self.gridLayout_3.addWidget(self.loadLastDb, 0, 0, 1, 1)
        self.crashSave = QtWidgets.QCheckBox(self.groupBox)
        self.crashSave.setObjectName("crashSave")
        self.gridLayout_3.addWidget(self.crashSave, 2, 0, 1, 1)
        self.backupDb = QtWidgets.QCheckBox(self.groupBox)
        self.backupDb.setObjectName("backupDb")
        self.gridLayout_3.addWidget(self.backupDb, 1, 0, 1, 1)
        self.ignoreNonPart = QtWidgets.QCheckBox(self.groupBox)
        self.ignoreNonPart.setObjectName("ignoreNonPart")
        self.gridLayout_3.addWidget(self.ignoreNonPart, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.instantSort = QtWidgets.QCheckBox(self.groupBox_2)
        self.instantSort.setObjectName("instantSort")
        self.gridLayout_4.addWidget(self.instantSort, 0, 0, 1, 1)
        self.wipeResults = QtWidgets.QCheckBox(self.groupBox_2)
        self.wipeResults.setObjectName("wipeResults")
        self.gridLayout_4.addWidget(self.wipeResults, 1, 0, 1, 1)
        self.guessGender = QtWidgets.QCheckBox(self.groupBox_2)
        self.guessGender.setObjectName("guessGender")
        self.gridLayout_4.addWidget(self.guessGender, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.templateLbl = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.templateLbl.sizePolicy().hasHeightForWidth())
        self.templateLbl.setSizePolicy(sizePolicy)
        self.templateLbl.setObjectName("templateLbl")
        self.gridLayout_5.addWidget(self.templateLbl, 0, 0, 1, 1)
        self.templateBtn = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.templateBtn.sizePolicy().hasHeightForWidth())
        self.templateBtn.setSizePolicy(sizePolicy)
        self.templateBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/menu_icons_16/open"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.templateBtn.setIcon(icon)
        self.templateBtn.setFlat(True)
        self.templateBtn.setObjectName("templateBtn")
        self.gridLayout_5.addWidget(self.templateBtn, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.sortBox = QtWidgets.QComboBox(self.groupBox_4)
        self.sortBox.setObjectName("sortBox")
        self.sortBox.addItem("")
        self.sortBox.addItem("")
        self.sortBox.addItem("")
        self.sortBox.addItem("")
        self.sortBox.addItem("")
        self.sortBox.addItem("")
        self.sortBox.addItem("")
        self.sortBox.addItem("")
        self.sortBox.addItem("")
        self.gridLayout_6.addWidget(self.sortBox, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 2, 0, 1, 2)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.okButton.clicked.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Einstellungen"))
        self.okButton.setText(_translate("Dialog", "&OK"))
        self.groupBox.setTitle(_translate("Dialog", "Allgemein"))
        self.loadLastDb.setText(_translate("Dialog", "Letzte Datenbank beim Start laden"))
        self.crashSave.setText(_translate("Dialog", "Absturzsicherung aktivieren (langsam!)"))
        self.backupDb.setText(_translate("Dialog", "Datenbanken vor Bearbeitung sichern (.ffd~)"))
        self.ignoreNonPart.setText(_translate("Dialog", "Nicht abgelegte Disziplinen ignorieren"))
        self.groupBox_2.setTitle(_translate("Dialog", "Datenbankeditor"))
        self.instantSort.setText(_translate("Dialog", "Daten sofort sortieren"))
        self.wipeResults.setText(_translate("Dialog", "Ergebnisse beim Speichern löschen"))
        self.guessGender.setText(_translate("Dialog", "Geschlecht raten"))
        self.groupBox_3.setTitle(_translate("Dialog", "Auswertung"))
        self.templateLbl.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Urkundenvorlage:</span><span style=\" font-family:\'monospace\'; color:#ff0000;\">&lt;kein&gt;</span></p></body></html>"))
        self.groupBox_4.setTitle(_translate("Dialog", "Standard-Sortierung"))
        self.sortBox.setItemText(0, _translate("Dialog", "Klasse → Nachname → Vorname*"))
        self.sortBox.setItemText(1, _translate("Dialog", "Klasse → Vorname → Nachname"))
        self.sortBox.setItemText(2, _translate("Dialog", "Nachname → Vorname"))
        self.sortBox.setItemText(3, _translate("Dialog", "Vorname → Nachname"))
        self.sortBox.setItemText(4, _translate("Dialog", "Klasse → Geschlecht"))
        self.sortBox.setItemText(5, _translate("Dialog", "Geschlecht → Nachname"))
        self.sortBox.setItemText(6, _translate("Dialog", "Geschlecht → Vorname"))
        self.sortBox.setItemText(7, _translate("Dialog", "Klasse"))
        self.sortBox.setItemText(8, _translate("Dialog", "andere..."))

import oxyicons_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

